### ISSUE TITLE
Release on OpenSUSE is outdated and broken?

### ISSUE THREAD

**Issue by krishjainx** [openSUSE/openSUSEway#129] opened 2024-01-17 04:39 UTC
Hi, the openSUSEway package (https://software.opensuse.org/package/openSUSEway) is still at version 0.15.2. There has been a lot of work done since then, so we should release new versions.

In addition, installing openSUSEway as suggested in the wiki presents this problem:

```
Could not activate session: Interactive authentication required.
```

I found a forum post reporting the same issue (https://forums.opensuse.org/t/sway-will-not-launch-on-fresh-install-minimal-desktop-does-the-installer-need-an-update/166534). Sway will not launch from the login manager after a fresh install of the openSUSEway pattern on OpenSUSE Tumbleweed. One has to manually launch sway from a TTY.

So the openSUSEway pattern in OpenSUSE Tumbleweed is currently broken.

In addition to this, launching the Alacritty terminal emulator in Sway presents the message "YAML config "/etc/alacritty/alacritty.yml" is deprecated, please migrate to TOML using "alacritty migrate"". However, migrating to TOML causes it to complain about the missing YAML file. This could be a packaging issue. 😓 

We should fix this.

**Comment by FilippoBonazziSUSE** [comment] 2024-01-17 11:45
> In addition to this, launching the Alacritty terminal emulator in Sway presents the message "YAML config "/etc/alacritty/alacritty.yml" is deprecated, please migrate to TOML using "alacritty migrate"".

This has just been fixed in #128

**Comment by FilippoBonazziSUSE** [comment] 2024-01-17 15:50
> In addition, installing openSUSEway as suggested in the wiki presents this problem:
> ```
> Could not activate session: Interactive authentication required.
> ```

This is another issue stll. I've never seen this one, I can try to replicate it.

**Comment by FilippoBonazziSUSE** [comment] 2024-01-17 16:25
I cannot reproduce this problem.

I have just succesfully installed an openSUSEway desktop by doing the following:

1. Boot up the ISO installer
2. Select Generic desktop
3. Get to the last step, click "Software", select "openSUSEway"
4. Reboot into the installed system
5. Login on the TTY and run
```
sudo systemctl set-default graphical.target
sudo systemctl enable greetd
```
6. Reboot and login in greetd

**Comment by jubalh** [comment] 2024-01-18 09:17
>  The issue, however, is that alacritty prompts me to migrate to TOML

Fixed in https://github.com/openSUSE/openSUSEway/pull/128
But needs to be pushed to OBS.

**Comment by FilippoBonazziSUSE** [comment] 2024-01-18 09:25
We are preparing the next release right now, as I told you yesterday.

Please try to report one problem per Issue, and keep unrelated issues separate.

**Closed by FilippoBonazziSUSE** 2024-01-18 09:25 UTC
