### ISSUE TITLE
A few appearance related suggestions

### ISSUE THREAD

**Issue by markosx32** [openSUSE/openSUSEway#146] opened 2024-03-03 14:48 UTC
I have been using opensuseway for the past month.
Normally i setup sway on my own on other distros, so it's refreshing that most of the "standard" chore-like appearance aspects of it have been handled by opensuseway and i can go ahead and do my particular modifications to a sane application & config base.

That being said i have noticed a few things that were rough around the edges:

1. I had to use `lxappearance` a very common and lightweight gtk theme switcher to set the theme to Adwaita-Dark because for some reason it was set to white after the latest opensuseway update. `lxappearance` is a very useful tool, commonly used in i3wm and sway setups and has very little dependencies.

2. The gtkgreet login screen is white and doesn't follow the adwaita-dark theme. While its fairly trivial to change, it's one of the 'chores' i want to avoid having to do using opensuseway.

3. Since the 'DE' is mostly driven using the command-line, it would be nice to have a more interactive-minded shell as the default, like zsh with the `grml-zsh-config` (or it could be a pattern suggestion at least)

4. The swaylock screen is setting a black background. It would be a bit more nice to have it set the background image used by the login screen and the sway environment. The path of the image already exists in the config so its a simple change, but helps a lot with first impressions.

5. The swaylock timer is way too fast (locks in 5 minutes), and a saner default would be closer to 15, which is what gnome/kde usually goes for as far as i remember.
Additionally when i override this in my `~/.config/sway/config.d/70-myconfig.conf` it has as an effect, both `exec swayidle commands to run` one from `/etc/sway/config,d/50-opensuseway.conf` and one from my local with different timers.
So i cannot override it and i have to comment out the config in `50-opensuseway.conf`

6. Potentially as more of an eye-candy we could also consider using `swaylock-effects` instead of `swaylock` which does a blurring of the background for the lockscreen bg, and supports clock & date, fade in/out etc.
(https://github.com/jirutka/swaylock-effects)

**Comment by denisok** [comment] 2024-03-04 14:42
Hi @markosx32 ,

Thank you for suggestions.

Theme is currently hardcoded in `50-openSUSE.conf`:
```
    gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
    gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
    gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
 ```
I installed `lxappearance` but it does nothing for me. It starts in light theme somehow...

> gtkgreet login
hm, strange. It is not white for me for sure, but I am running it too long, maybe I have some settings that tweaks it.

>  like zsh

oh, this a holy war - which shell to use. IMHO it is something left to the user to tweak.

>The swaylock screen is setting a black background
I agree :) If you could - maybe you can submit PR with it, otherwise we will try to pick up it ourselves for the next release.

>The swaylock timer is way too fast (locks in 5 minutes), and a saner default would be closer to 15
yes, 15 is probably maximum by security standard. I don't mind 15.

>swaylock-effects instead of swaylock
I don't mind it either. We need more feedback from community. Maybe we need to re-open https://github.com/openSUSE/openSUSEway/issues/39 with new repo suggestion.

**Comment by FilippoBonazziSUSE** [comment] 2024-03-04 16:15
Some comments from me as well

>  I had to use lxappearance a very common and lightweight gtk theme switcher to set the theme to Adwaita-Dark because for some reason it was set to white after the latest opensuseway update.

I've never seen this. Are you on Tumbleweed? What openSUSEway version do you have? Do you have any `rpmnew` or `rpmsave` files for openSUSEway-related config files?

> The gtkgreet login screen is white and doesn't follow the adwaita-dark theme.

I don't know if I've ever seen this either. Are you sure you have the right configuration files in place, with no errors etc?

> Since the 'DE' is mostly driven using the command-line, it would be nice to have a more interactive-minded shell as the default, like zsh with the grml-zsh-config (or it could be a pattern suggestion at least)

Agreed with denisok, this is a topic best left to the user.

> The swaylock screen is setting a black background. It would be a bit more nice to have it set the background image used by the login screen and the sway environment. The path of the image already exists in the config so its a simple change, but helps a lot with first impressions.

Sure, feel free to open a PR for it or we can pick it up ourselves sometime as well.

> The swaylock timer is way too fast (locks in 5 minutes), and a saner default would be closer to 15, which is what gnome/kde usually goes for as far as i remember.

When we do some work in this area, we can also incorporate [chayang](https://git.sr.ht/~emersion/chayang) which I [packaged](https://build.opensuse.org/package/show/X11:Wayland/chayang) almost one year ago and then never included.

> Additionally when i override this in my ~/.config/sway/config.d/70-myconfig.conf it has as an effect, both exec swayidle commands to run one from /etc/sway/config,d/50-opensuseway.conf and one from my local with different timers.
    So i cannot override it and i have to comment out the config in 50-opensuseway.conf

Yes, this is unfortunate and we've had it open as a discussion topic for a long time (https://github.com/openSUSE/openSUSEway/issues/49). Hopefully we can get around to improving this sometime. I have some ideas on how to do this (discussed in the linked issue) but lack the time.

> Potentially as more of an eye-candy we could also consider using swaylock-effects instead of swaylock which does a blurring of the background for the lockscreen bg, and supports clock & date, fade in/out etc.
    (https://github.com/jirutka/swaylock-effects)

This looks nice, but the upstream situation seems confusing. I personally don't care about this as I'm perfectly happy with the basic `swaylock`.

In general please try to open one Issue per topic, otherwise it is impossible to properly track their status. So please open individual Issues for any of the above topics that don't have one.

**Comment by antisocrates** [comment] 2024-03-08 02:18
Especially the swaylock timer override issue should be fixed asap.

**Comment by FilippoBonazziSUSE** [comment] 2024-03-08 16:37
> I had to use lxappearance a very common and lightweight gtk theme switcher to set the theme to Adwaita-Dark because for some reason it was set to white after the latest opensuseway update.

Cannot reproduce, feel free to open a separate issue if you still see this.

> The gtkgreet login screen is white and doesn't follow the adwaita-dark theme.

Cannot reproduce, feel free to open a separate issue if you still see this.

> Since the 'DE' is mostly driven using the command-line, it would be nice to have a more interactive-minded shell as the default, like zsh with the grml-zsh-config (or it could be a pattern suggestion at least)

We do not want to do this, as we believe this is a topic best left to the user.

> The swaylock screen is setting a black background. It would be a bit more nice to have it set the background image used by the login screen and the sway environment. The path of the image already exists in the config so its a simple change, but helps a lot with first impressions.

Moved to #149.

> The swaylock timer is way too fast (locks in 5 minutes), and a saner default would be closer to 15, which is what gnome/kde usually goes for as far as i remember.

Moved to #150.

> Additionally when i override this in my ~/.config/sway/config.d/70-myconfig.conf it has as an effect, both exec swayidle commands to run one from /etc/sway/config,d/50-opensuseway.conf and one from my local with different timers.
    So i cannot override it and i have to comment out the config in 50-opensuseway.conf

See #49.

> Potentially as more of an eye-candy we could also consider using swaylock-effects instead of swaylock which does a blurring of the background for the lockscreen bg, and supports clock & date, fade in/out etc.
    (https://github.com/jirutka/swaylock-effects)

Moved to #151.

**Closed by FilippoBonazziSUSE** 2024-03-08 16:37 UTC
